[[plugins]]
  package = "netlify-plugin-rss"

    [plugins.inputs]
    # required configs, customize as needed
    dirToScan = "/cache" # a subfolder to scan. "/" to scan all
    authorName = "Nikita"
    site_url = "https://silly-johnson-a7726f.netlify.app/"
    title = "search test RSS Feed"
    rssDescription = "search test RSS Feed"
    categories = ['Technology', 'JAMstack', 'Web Development']